# Generated by Django 4.0.6 on 2022-08-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makalelermodel',
            name='icerik',
            field=models.FileField(upload_to='makale_pdf'),
        ),
    ]
