# Generated by Django 4.0.6 on 2022-08-16 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_rename_icerik_makalelermodel_makale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makalelermodel',
            name='duzenlenme_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='makalelermodel',
            name='yazar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makaleler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yazilarmodel',
            name='duzenlenme_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='yorummodel',
            name='duzenlenme_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
