# Generated by Django 4.0.6 on 2022-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_yazilarmodel_yazar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makalelermodel',
            name='duzenlenme_tarihi',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='makalelermodel',
            name='olusturulma_tarihi',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='yazilarmodel',
            name='duzenlenme_tarihi',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='yazilarmodel',
            name='olusturulma_tarihi',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='yorummodel',
            name='duzenlenme_tarihi',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='yorummodel',
            name='olusturulma_tarihi',
            field=models.DateTimeField(editable=False),
        ),
    ]
