# Generated by Django 4.0.6 on 2022-09-12 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models.yazi


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_alter_makalelermodel_yazar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazilarmodel',
            name='yazar',
            field=models.ForeignKey(default=website.models.yazi.YazilarModel, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='yazilar', to=settings.AUTH_USER_MODEL),
        ),
    ]
