# Generated by Django 4.0.6 on 2022-09-21 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0012_alter_yazilarmodel_yazar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makalelermodel',
            name='makale',
            field=models.FileField(null=True, upload_to='makale_pdf'),
        ),
        migrations.AlterField(
            model_name='yazilarmodel',
            name='yazar',
            field=models.ForeignKey(default='ozturkurtulus@gmail.com', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='yazilar', to=settings.AUTH_USER_MODEL),
        ),
    ]
