# Generated by Django 4.0.6 on 2022-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_makalelermodel_makale_alter_yazilarmodel_yazar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makalelermodel',
            name='makale',
            field=models.ImageField(null=True, upload_to='makale_pdf'),
        ),
    ]
