# Generated by Django 4.0.6 on 2022-09-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_makalelermodel_makale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makalelermodel',
            name='makale',
            field=models.FileField(null=True, upload_to='makale_pdf'),
        ),
    ]
