# Generated by Django 4.0.6 on 2022-09-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_yazilarmodel_yazar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makalelermodel',
            name='makale',
            field=models.FileField(null=True, upload_to='makale_pdf'),
        ),
    ]
